version: '3'

networks:
  infra_kwsnet:
    external: true

services:
  tensorflow_jupyter:
    build: ./
    image: study_tensor
    container_name: kwsnet-jupyter-container
    restart: always
    env_file:
      - ./.env
    networks:
      - infra_kwsnet
    volumes:
      - ../notebook:/tf/notebooks